### ISSUE TITLE
ipfs version not working

### ISSUE THREAD

**Issue by zapaz** [Kredeum/flashsuite#7]
ipfs version not working

**Comment by zapaz** [comment]
probably due to mix of  absolute / relative or standard / ipfs links ?

**Comment by ra-phael** [comment]
Maybe because it fails to build, I had the problem locally.

From the rollup config:
`toRollupConfig('flashaccounts')`

whereas the name differs in the svelte folder: `FlashAccounts.js`

**Comment by zapaz** [comment]
yes possible case pb, try to set everything lowercase

**Comment by zapaz** [comment]
working now
